// A release draft as text: the statements the release would sign, in C-SQL,
// then its warnings and refusals. Pins read LATEST, as target-catalog.sql
// states them; the signed release pins exact entries.

import {
    renderIdent, renderLiteral, renderMigrationRule, renderSourceCreators, renderSourceFiles, renderSourceGroup, renderSourceParams, renderSourceSchema,
    type SourceKeyLabels,
} from "@hyper-hyper-space/hhs3_rdb_lang";

import type { ReleaseDraft } from "./draft.js";
import { SOURCE_FILE, UPGRADE_MANUAL_FILE } from "./project.js";
import { describeRelease, type ReleaseInfo } from "./released.js";
import { formatWhere } from "./source.js";

const UPGRADE_HEADER = [
    '-- Generated by `rpack build`. Do not edit.',
    `-- Edit the catalog's end state in ${SOURCE_FILE}.`,
    '-- This file is the release: the previous releases, then the steps in',
    `-- ${UPGRADE_MANUAL_FILE}, then the difference from ${SOURCE_FILE}.`,
    `-- A step the diff cannot infer (a column reset, for example) goes in ${UPGRADE_MANUAL_FILE}.`,
].join('\n');

function quote(version: string): string {
    return renderLiteral(version);
}

// The C-SQL the release would sign: schema creates and updates, then the
// catalog statement. No title, warnings, or refusals. A blank line separates
// statements.
export function formatDraftSql(plan: ReleaseDraft, labels?: SourceKeyLabels): string[] {
    if (plan.refusals.length > 0) return [];
    const lines: string[] = [];
    for (const step of plan.schemas) {
        if (lines.length > 0) lines.push('');
        if (step.kind === 'create') {
            lines.push(...renderSourceSchema({
                name: step.schema.name,
                creators: step.schema.creators,
                ...(step.schema.hashAlgorithm !== undefined ? { hashAlgorithm: step.schema.hashAlgorithm } : {}),
                tables: [...step.schema.tables.values()],
            }, labels).replace(/ AS \(\n/, ` VERSION ${quote(step.version)} AS (\n`).split('\n'));
            continue;
        }
        const rules = step.rules.map((r, i) => {
            const separator = i < step.rules.length - 1 ? ',' : '';
            const comment = r.where !== undefined ? `    -- ${r.where.file}:${r.where.line}` : '';
            return `  ${renderMigrationRule(r.rule)}${separator}${comment}`;
        });
        lines.push(`ALTER SCHEMA ${renderIdent(step.schema)} VERSION ${quote(step.version)} AS (`, ...rules.join('\n').split('\n'), ');');
    }

    if (lines.length > 0) lines.push('');
    if (plan.first) {
        const desired = plan.desired;
        const head = [`CREATE CATALOG ${renderIdent(plan.catalog)}`];
        const creators = renderSourceCreators(desired.creators, labels);
        if (creators.length > 0) head.push(creators);
        head.push(`VERSION ${quote(plan.version)}`);
        const params = renderSourceParams(plan.params);
        if (params.length > 0) head.push(params);
        if (desired.seed !== undefined) head.push(`SEED ${renderLiteral(desired.seed)}`);
        if (desired.hashAlgorithm !== undefined) head.push(`HASH ALGORITHM ${renderLiteral(desired.hashAlgorithm)}`);
        const groups = plan.add.map((g) => renderSourceGroup(g, { ...(labels !== undefined ? { labels } : {}), pin: 'LATEST' }));
        const files = plan.addFiles.map((f) => renderSourceFiles(f));
        lines.push(...`${head.join(' ')} AS (\n  ${[...groups, ...files].join(',\n  ')}\n);`.split('\n'));
    } else {
        const head = [`ALTER CATALOG ${renderIdent(plan.catalog)}`, `VERSION ${quote(plan.version)}`];
        const params = renderSourceParams(plan.params);
        if (params.length > 0) head.push(params);
        const body = [
            ...plan.changes.map((c) => `UPDATE SCHEMA ${renderIdent(c.schema)} TO LATEST ON ${renderIdent(c.group)}`),
            ...plan.add.map((g) => renderSourceGroup(g, { ...(labels !== undefined ? { labels } : {}), keyword: 'ADD TABLEGROUP', pin: 'LATEST' })),
            ...plan.addFiles.map((f) => renderSourceFiles(f, { keyword: 'ADD FILES' })),
        ];
        const text = body.length > 0 ? `${head.join(' ')} AS (\n  ${body.join(',\n  ')}\n);` : `${head.join(' ')};`;
        lines.push(...text.split('\n'));
    }
    return lines;
}

// update.sql: the header, a blank line, and the statements. Callers write it
// only for a draft that was not refused.
export function formatUpgrade(plan: ReleaseDraft, labels?: SourceKeyLabels): string {
    return `${UPGRADE_HEADER}\n\n${formatDraftSql(plan, labels).join('\n')}\n`;
}

export function formatDraft(plan: ReleaseDraft, labels?: SourceKeyLabels): string[] {
    const lines: string[] = [];
    const from = plan.first ? 'the first release' : `from ${plan.parents.map(describeRelease).join(' + ')}`;
    lines.push(`${plan.catalog} ${plan.version}, ${from}`);

    if (plan.refusals.length > 0) {
        lines.push('', 'refused');
        for (const refusal of plan.refusals) {
            lines.push(`  ${formatWhere(refusal.where)}${refusal.message}`);
            if (refusal.hint !== undefined) lines.push(`    ${refusal.hint}`);
        }
        return lines;
    }

    lines.push('', ...formatDraftSql(plan, labels));

    if (plan.warnings.length > 0) {
        lines.push('', 'warnings');
        for (const warning of plan.warnings) lines.push(`  ${warning}`);
    }
    return lines;
}

function countPhrase(n: number, verb: string, one: string, many: string): string | undefined {
    if (n === 0) return undefined;
    return `${verb} ${n} ${n === 1 ? one : many}`;
}

// The lines every status starts with: the catalog, the version, its base, and
// for a released folder, the release made from it.
export function statusHeader(catalog: string, version: string, base: string, released?: string): string[] {
    return [
        `Catalog "${catalog}"`,
        '',
        `Version: ${version}`,
        `Base: ${base}`,
        ...(released !== undefined ? [released] : []),
    ];
}

// A failure before a draft exists: the header, then that the version could not
// be assembled, then each detail (a source location, or a message with none).
export function formatStatusError(catalog: string, version: string, base: string, detail: string[], released?: string): string[] {
    return [...statusHeader(catalog, version, base, released), '', `Error assembling ${version}`, ...detail];
}

// The count line `status` prints for a draft that was not refused.
export function statusSummary(plan: ReleaseDraft): string {
    let addedSchemas = 0;
    let addedTables = 0;
    let addedColumns = 0;
    let droppedColumns = 0;
    let foreignKeys = 0;
    let restrictions = 0;
    let concurrentDeletes = 0;
    let droppedTables = 0;
    for (const step of plan.schemas) {
        if (step.kind === 'create') {
            addedSchemas += 1;
            addedTables += step.schema.tables.size;
            continue;
        }
        for (const { rule } of step.rules) {
            switch (rule.rule) {
                case 'add-table': addedTables += 1; break;
                case 'drop-table': droppedTables += 1; break;
                case 'add-column': addedColumns += 1; break;
                case 'drop-column': droppedColumns += 1; break;
                case 'set-fks': foreignKeys += 1; break;
                case 'set-restrictions': restrictions += 1; break;
                case 'set-concurrent-deletes': concurrentDeletes += 1; break;
            }
        }
    }
    const phrases = [
        countPhrase(addedSchemas, 'added', 'schema', 'schemas'),
        countPhrase(addedTables, 'added', 'table', 'tables'),
        countPhrase(addedColumns, 'added', 'column', 'columns'),
        countPhrase(foreignKeys, 'changed', 'foreign key', 'foreign keys'),
        countPhrase(restrictions, 'changed', 'restriction', 'restrictions'),
        countPhrase(concurrentDeletes, 'changed', 'concurrent delete', 'concurrent deletes'),
        countPhrase(droppedTables, 'dropped', 'table', 'tables'),
        countPhrase(droppedColumns, 'dropped', 'column', 'columns'),
        countPhrase(plan.add.length, 'added', 'group', 'groups'),
        countPhrase(plan.addFiles.length, 'added', 'FILES', 'FILES'),
        countPhrase(plan.changes.length, 'set', 'group', 'groups'),
        countPhrase(plan.params.length, 'added', 'param', 'params'),
    ].filter((p) => p !== undefined);
    return phrases.length > 0 ? phrases.join(', ') : 'nothing to release';
}

// What `rpack release` prints before asking. Warnings follow the count under
// one heading; with none, the count stands alone.
export function formatReleaseConfirm(plan: ReleaseDraft): string[] {
    const lines = [statusSummary(plan)];
    if (plan.warnings.length > 0) lines.push('', 'Warning:', ...plan.warnings);
    return lines;
}

// A released dependent of a re-release, built again on it.
export type RebuiltRelease = {
    folder: string;
    replaces: ReleaseInfo;
    draft: ReleaseDraft;
    // The folder's signed inputs, base or note differ from what `replaces` was made from.
    edited: boolean;
};

// What a release would do, shown before anything is written.
export type ReleasePreview = {
    catalog: string;
    draft: ReleaseDraft;
    // For a re-release: the release it replaces, the released dependents built
    // again on it (by version), and the unreleased folders whose version.json
    // names a replaced release.
    replaces?: ReleaseInfo;
    rebuilt: RebuiltRelease[];
    repointed: string[];
};

export function formatReleasePreview(preview: ReleasePreview): string[] {
    const replaced = preview.replaces;
    if (replaced === undefined) return formatReleaseConfirm(preview.draft);
    const lines = [`Re-releasing ${preview.draft.version} replaces ${replaced.name}.`, ...formatReleaseConfirm(preview.draft)];
    if (replaced.parents.length === 0) {
        lines.push('', `${replaced.version} is the first release: the re-release starts a new catalog, and replicas of the old one take none of its releases.`);
    }
    if (preview.rebuilt.length > 0) {
        const n = preview.rebuilt.length;
        lines.push('', `It also re-releases ${n} ${n === 1 ? 'release' : 'releases'} built on it:`);
        for (const r of preview.rebuilt) {
            lines.push(`  ${r.draft.version}  replaces ${r.replaces.name}${r.edited ? '  (changed since release)' : ''}`);
            lines.push(...formatReleaseConfirm(r.draft).map((l) => (l === '' ? '' : `    ${l}`)));
        }
    }
    for (const folder of preview.repointed) {
        lines.push('', `work/${folder}/ is written against the old ${replaced.version}; its version.json will name the new one: check it.`);
    }
    const all = [replaced, ...preview.rebuilt.map((r) => r.replaces)];
    lines.push('', `Copies of ${all.map((r) => r.name).join(', ')} already shared stay valid releases: a replica that has one would hold it next to the new ${all.length === 1 ? 'one' : 'ones'}.`);
    return lines;
}

// The release under way: catalog, version, base, then a count of the draft's
// shape. Refusals replace the count. Warnings are a count; `formatDraft` prints them.
export function formatStatus(plan: ReleaseDraft, released?: string): string[] {
    const base = plan.first ? 'None, this is the first release' : plan.parents.map(describeRelease).join(' + ');
    const lines = statusHeader(plan.catalog, plan.version, base, released);
    lines.push('');
    if (plan.refusals.length > 0) {
        lines.push('refused');
        for (const refusal of plan.refusals) {
            lines.push(`  ${formatWhere(refusal.where)}${refusal.message}`);
            if (refusal.hint !== undefined) lines.push(`    ${refusal.hint}`);
        }
        return lines;
    }

    lines.push(statusSummary(plan));
    if (plan.warnings.length > 0) lines.push(`${plan.warnings.length} ${plan.warnings.length === 1 ? 'warning' : 'warnings'}`);
    return lines;
}
